name: Sync Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 执行
  workflow_dispatch:    # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. 确保 fatigue_data.csv 文件存在，若不存在则创建
      - name: Ensure fatigue_data.csv exists
        run: |
          if [ ! -f "fatigue_data.csv" ]; then
            echo "Creating fatigue_data.csv..."
            echo "颈部前屈,颈部后仰,肩部上举范围,肩部前伸范围,肘部屈伸,手腕背伸,手腕桡偏/尺偏,背部屈曲范围,持续时间,重复频率,fatigue_result" > fatigue_data.csv
          else
            echo "fatigue_data.csv already exists."
          fi

      # 2. 打印当前目录中的文件，确保 fatigue_data.csv 文件确实存在
      - name: List files in the directory
        run: ls -l

      # 3. 获取最新代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 4. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      # 5. 安装依赖
      - name: Install dependencies
        run: pip install pandas

      # 6. 查看当前 Git 状态，确认是否有变更
      - name: Check git status
        run: git status

      # 7. 清除 Git 缓存并强制重新添加文件
      - name: Clean Git cache and add changes
        run: |
          git rm -r --cached .   # 清除所有文件的缓存
          git add fatigue_data.csv   # 重新添加 fatigue_data.csv 文件
          git status   # 查看当前状态，确保文件被添加

      # 8. 查看文件是否被正确跟踪
      - name: Check if fatigue_data.csv is tracked by Git
        run: |
          if git ls-files --error-unmatch fatigue_data.csv; then
            echo "fatigue_data.csv is tracked by Git."
          else
            echo "fatigue_data.csv is not tracked by Git."
          fi

      # 9. 提交并推送更改
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 确保文件被正确添加并检查 Git 状态
          git add fatigue_data.csv
          git status   # 确认文件是否被添加

          # 如果有变更则提交
          git commit -m "Update fatigue_data.csv with new data" || echo "No changes to commit"
          git diff   # 查看具体差异

          # 拉取最新代码并推送
          git pull origin main --rebase
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
